<?php

namespace ContainerJs1lyvM;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEvent_JwtCreatedListenerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'event.jwt_created_listener' shared autowired service.
     *
     * @return \App\Event\Listener\JWTCreatedListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Event'.\DIRECTORY_SEPARATOR.'Listener'.\DIRECTORY_SEPARATOR.'JWTCreatedListener.php';

        return $container->privates['event.jwt_created_listener'] = new \App\Event\Listener\JWTCreatedListener(($container->services['.container.private.security.token_storage'] ?? $container->get_Container_Private_Security_TokenStorageService()));
    }
}
