<?php

namespace ContainerJs1lyvM;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHeaderAuthGeneratorService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\HeaderAuthGenerator' shared autowired service.
     *
     * @return \App\Service\HeaderAuthGenerator
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'HeaderAuthGenerator.php';

        return $container->privates['App\\Service\\HeaderAuthGenerator'] = new \App\Service\HeaderAuthGenerator(($container->privates['App\\Repository\\ConfigKeysRepository'] ?? $container->load('getConfigKeysRepositoryService')));
    }
}
