<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJs1lyvM\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJs1lyvM/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJs1lyvM.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJs1lyvM\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerJs1lyvM\App_KernelDevDebugContainer([
    'container.build_hash' => 'Js1lyvM',
    'container.build_id' => '3aba3513',
    'container.build_time' => 1653499238,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJs1lyvM');
